export enum NPCNames {
  TheOldLady = "The Old Lady",
  TheBartender = "The Bartender",
  TheOldMan = "The Old Man",
  TheYoungWoman = "The Young Woman",
  Ella = "Strange Lady",
  Bård = "Strange Pig",
  Lums = "Wild Chocobo",
}

export enum QuestStages {
  NotStarted = "Not Started",
  InProgress = "In Progress",
  Completed = "Completed",
}

export enum QuestNames {
  SecretIngredient = "Secret Ingredient",
  FirstTrial = "Trial Of The Siren's Song",
  SecondTrial = "Second Trial",
  ThirdTrial = "Third Trial",
  FourthTrial = "Fourth Trial",
  FifthTrial = "Fifth Trial",
  SixthTrial = "Sixth Trial",
  MysteriousBox = "Mysterious Box",
  BårdQuestOne = "Forbidden Fruit",
  BårdQuestTwo = "The Thief",
  EllaQuestOne = "Forbidden Juice",
  EllaQuestTwo = "Steaks are high",
  BartenderOne = "Catch Of The Day",
  BartenderTwo = "Beastly Bother",
  LumsQuestOne = "The Zu's Gotta Go",
}

export enum Locations {
  Tavern = "Tavern",
  outsideTavern = "Ironwood Avenue",
  BackGate = "Ironwood Gate",
  EmeraldPlaza = "Emerald Plaza",
  CityGates = "Aranthria City Gates",
  EvershadeForest = "Evershade Forest",
  TheCrystalCaves = "Crystal Caves",
  ElderglowLake = "Elderglow Lake",
  Eldervale = "Eldervale",
  CircleOfTheGods = "Circle Of The Gods",
  AetherPeak = "Aether Peak",
  EaglesPeak = "Eagles Peak",
  ArmorShop = "Armor Shop",
  tavernRoom = "Tavern Room",
  WhisperingWoods = "Whispering Woods",
  RiverbendHarbor = "Riverbend Harbor",
  harbor = "Harbor",
  BlackVoid = "Black Void",
  PotionShop = "Potion Shop",
  EloweensCabin = "Eloween's Cabin",
  MoonlitPool = "Moonlit Pool",
  SingingGrove = "The Singing Grove",
  WhisperingCavern = "Whispering Cavern",
  PathToCave = "Harbor Path",
  ForestPath = "Forest Path",
  Blacksmith = "Blacksmith Shop",
  RiverbendBeach = "Riverbend Beach",
  RestRoom = "Your Tavern Room",
}

export enum Loot {
  FeatherLeafSkeleton = "Feather Leaf Skeleton",
  FeatherLeafFluid = "Feather Leaf Fluid",
  SirenSkull = "Siren Skull",
  SirenScale = "Siren Scale",
  EagleSkull = "Eagle Queen Skull",
  MirewalkerSkull = "Mirewalker Skull",
  GrimLurkerPoison = "Grim Lurker Poison",
  MarasnakeSkull = "Marasnake Skull",
  DragonSkull = "Dragon Skull",
  DragonEgg = "Dragon Egg",
  ZuSkull = "Zu Skull",
  Ring = "Magic Ring",
  GlowfinMinnowMeat = "Glowfin Minnow Meat",
  HellmawPiranhaMeat = "Hellmaw Piranha Meat",
}
