import { QuestItemNames } from "./questItems";
import { NPCNames, QuestNames, QuestStages } from "../Enums";
import { Quest } from "../objects/Quest";

export const QuestList: Quest[] = [
  {
    name: QuestNames.SecretIngredient,
    description: [
      "I want to make my famous meal, but none of the stores have any! ",
      "The meat are from the little Feather Leafs in the cave, but that is way to dangerous for an old lady like me. ",
      "Could i bother you with fetching some for me? one should be plenty!",
    ],
    reward: 10,
    questItem: [QuestItemNames.FeatherLeafMeat],
    status: QuestStages.NotStarted,
    npc: NPCNames.TheOldLady,
    xp: 50,
    lvl: 1,
  },
  {
    name: QuestNames.test,
    description: ["This is a test"],
    reward: 10,
    questItem: [],
    status: QuestStages.NotStarted,
    npc: NPCNames.TheBartender,
    xp: 50,
    lvl: 1,
  },
  {
    name: QuestNames.FirstTrial,
    description: [
      "Excellent! For your first trial, you will need to travel south from here.",
      "You will need to find Elderglow Lake. There is a Siren there, who has been scaring away the villagers.",
      "Kill the monster, and retrieve her head for me.",
    ],
    reward: 20,
    questItem: [],
    status: QuestStages.NotStarted,
    npc: NPCNames.TheOldMan,
    xp: 100,
    lvl: 1,
  },
  {
    name: QuestNames.SecondTrial,
    description: ["This is a test"],
    reward: 30,
    questItem: [],
    status: QuestStages.NotStarted,
    npc: NPCNames.TheOldMan,
    xp: 150,
    lvl: 2,
  },
  {
    name: QuestNames.ThirdTrial,
    description: ["This is a test"],
    reward: 40,
    questItem: [],
    status: QuestStages.NotStarted,
    npc: NPCNames.TheOldMan,
    xp: 200,
    lvl: 3,
  },
  {
    name: QuestNames.FourthTrial,
    description: ["This is a test"],
    reward: 50,
    questItem: [],
    status: QuestStages.NotStarted,
    npc: NPCNames.TheOldMan,
    xp: 250,
    lvl: 4,
  },
  {
    name: QuestNames.FifthTrial,
    description: ["This is a test"],
    reward: 60,
    questItem: [],
    status: QuestStages.NotStarted,
    npc: NPCNames.TheOldMan,
    xp: 300,
    lvl: 5,
  },
  {
    name: QuestNames.SixthTrial,
    description: ["This is a test"],
    reward: 80,
    questItem: [],
    status: QuestStages.NotStarted,
    npc: NPCNames.TheOldMan,
    xp: 400,
    lvl: 6,
  },
  {
    name: QuestNames.MysteriousBox,
    description: [
      "The forest does not lie, you have come at a most opportune time.",
      "I have this box. It is said to hold a mysterious artifact, which has the power to heal the land.",
      "Unfortunately, the three keys are missing. Each key lies in a place guarded by a guardian.",
      "The first key's Guardian is by a moonlit pool, it is said to be an abyssal seahorse. You will need its heart for the key",
      "The second guardian is said to be in the Singing Grove. The Guardian is a dark druid. It is said that he wears the key around his neck.",
      "The third and last key, can be found in the Whispering Cavern. Be careful, in there lies a woman with a dangerous beast. You will need her headpiece for the key.",
    ],
    reward: 60,
    questItem: [
      QuestItemNames.KeyOne,
      QuestItemNames.KeyTwo,
      QuestItemNames.keyThree,
    ],
    status: QuestStages.NotStarted,
    npc: NPCNames.TheYoungWoman,
    xp: 300,
    lvl: 1,
  },
];
